name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend com Maven
        run: mvn -f backend/pom.xml clean install -DskipTests

      - name: Testa
        run: mvn -f backend/pom.xml test

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instala dependências e build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Publica no site do Github
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3

      - name: Checar segurança backend
        run: mvn -f backend/pom.xml org.owasp:dependency-check-maven:check

      - name: Checar segurança frontend
        run: |
          cd frontend
          npm audit --audit-level=high
